matrix:
  include:
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd client
      script:
        - echo "Test front"
    - language: python
      python: 3.6
      services:
        - docker
      script:
        - echo "Test back"
        - make build-deploy
      after_success:
        - echo $TRAVIS_BRANCH
        - if [[ $TRAVIS_PULL_REQUEST == “false” ]] && [[ $TRAVIS_BRANCH == “master” ]];
          then
            docker login -u $DOCOYOU -p $DOCOPA
            docker push mokemon/thesproj;
          fi

notifications:
  email:
    - beochot@protonmail.com