matrix:
  include:
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd client
      script:
        - echo "Test front"
    - language: python
      python: 3.6
      services:
        - docker
      script:
        - echo "Test back"
        - make build-deploy
      after_success:
        - |
          if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'master' ]]; then
            echo $DOCOPA | docker login -u $DOCOYOU --password-stdin;
            docker push mokemon/thesproj;
          else
            echo $TRAVIS_PULL_REQUEST;
            echo $TRAVIS_BRANCH;
          fi

notifications:
  email:
    - beochot@protonmail.com