matrix:
  include:
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd client
      script:
        - echo "Test front"
    - language: python
      python: 3.6
      services:
        - docker
      script:
        - echo "Test back"
        - make build-deploy

notifications:
  email:
    - beochot@protonmail.com