version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: |
            pwd
            ls
            make build-deploy
            if [ $CIRCLE_BRANCH = master ]; then 
              echo "Test"
              echo $DOCOPA | docker login -u $DOCOYOU --password-stdin;
              docker push mokemon/thesproj;
            fi
      