version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Building
          command: |
            cp -rf ./client/ ./server/src/main/resources/public/
	          docker build -t mokemon/thesproj .
            if [ $CIRCLE_BRANCH = master ]; then 
              echo "Test"
              echo $DOCOPA | docker login -u $DOCOYOU --password-stdin;
              docker push mokemon/thesproj;
            fi
