version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building frontend
          command: cp -rf ./client/ ./server/src/main/resources/public/
      - run:
          name: Building Docker image
          command: docker build -t mokemon/thesproj .
      - run:
          name: Pushing Docker image
          command: |
              if [ $CIRCLE_BRANCH = master ]; then 
                echo "Test"
                docker login -u $DOCOYOU -p $DOCOPA;
                docker push mokemon/thesproj;
              fi
